// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace GujianCodeCollection.Entity
{

    public class Data
    {

        [JsonProperty("total")]
        public int Total { get; set; }

        [JsonProperty("cards")]
        public string[] Cards { get; set; }
    }

    public class Code_Sina
    {

        [JsonProperty("k")]
        public bool K { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

}
